version: "3.7"

services:
  server:
    image: node:14-alpine
    command: sh -c "yarn install && yarn start:dev"
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./:/app
    env_file: ./.env

  postgres:
    restart: always
    env_file: ./.env
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:alpine

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    logging:
      driver: none

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "9091:8081"

volumes:
  postgres:
